# Generated by Django 3.1 on 2020-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(default='', max_length=100)),
                ('industyarea', models.CharField(default='', max_length=100)),
                ('monthlysalary_min', models.CharField(default='', max_length=15)),
                ('monthlysalary_max', models.CharField(default='', max_length=15)),
                ('joblocation', models.CharField(default='', max_length=100)),
                ('employment_type', models.CharField(default='', max_length=100)),
                ('number_of_positions', models.CharField(default='', max_length=10)),
                ('experience_required', models.CharField(default='', max_length=100)),
                ('brief_description_of_job', models.CharField(default='', max_length=200)),
                ('job_description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobprofile', models.CharField(default='', max_length=100)),
                ('numberofopenings', models.CharField(default='', max_length=10)),
                ('jobdescription', models.CharField(default='', max_length=500)),
                ('skillsrequired', models.CharField(default='', max_length=100)),
                ('jobresponsibilities', models.CharField(default='', max_length=100)),
                ('monthlystipend', models.CharField(default='', max_length=10)),
                ('perks', models.CharField(default='', max_length=10)),
                ('jobtype', models.CharField(default='', max_length=100)),
                ('companytype', models.CharField(default='', max_length=100)),
                ('worktime', models.CharField(default='', max_length=5)),
                ('jobbrief', models.CharField(default='', max_length=200)),
                ('joblocation', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
