# Generated by Django 3.1 on 2019-12-28 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('username', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_candidate_Username', message='Username should be of form e.g C20CO101', regex='^C[0-9]{2}[A-Z]{2}[0-9]{3}$')])),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerInfo',
            fields=[
                ('username', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_employer_Username', message='Username should be of form e.g E19CO101', regex='^E[0-9]{2}[A-Z]{2}[0-9]{3}$')])),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
