# Generated by Django 3.1 on 2020-01-06 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(default='', max_length=100)),
                ('industryarea', models.CharField(default='', max_length=100)),
                ('monthlysalary_min', models.CharField(default='', max_length=15)),
                ('monthlysalary_max', models.CharField(default='', max_length=15)),
                ('joblocation', models.CharField(default='', max_length=100)),
                ('employment_type', models.CharField(default='', max_length=100)),
                ('number_of_positions', models.CharField(default='', max_length=10)),
                ('experience_required', models.CharField(default='', max_length=100)),
                ('brief_description_of_job', models.CharField(default='', max_length=200)),
                ('job_description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobprofile', models.CharField(default='', max_length=100)),
                ('numberofopenings', models.CharField(default='', max_length=10)),
                ('jobdescription', models.CharField(default='', max_length=500)),
                ('skillsrequired', models.CharField(default='', max_length=100)),
                ('jobresponsibilities', models.CharField(default='', max_length=100)),
                ('monthlystipend', models.CharField(default='', max_length=10)),
                ('perks', models.CharField(default='', max_length=10)),
                ('jobtype', models.CharField(default='', max_length=100)),
                ('companytype', models.CharField(default='', max_length=100)),
                ('worktime', models.CharField(default='', max_length=5)),
                ('jobbrief', models.CharField(default='', max_length=200)),
                ('joblocation', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('jobprofile', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=200)),
                ('mobilenumber', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}$')])),
                ('website', models.CharField(default='', max_length=50)),
                ('aboutme', models.CharField(default='', max_length=200)),
                ('specialities', models.CharField(default='', max_length=100)),
                ('jobexperience', models.CharField(default='', max_length=50)),
                ('age', models.CharField(default='', max_length=3)),
                ('graduation', models.CharField(default='', max_length=100)),
                ('educationlevel', models.CharField(default='', max_length=50)),
                ('college', models.CharField(default='', max_length=100)),
                ('collegedegree', models.CharField(default='', max_length=50)),
                ('collegepercentage', models.CharField(default='', max_length=2)),
                ('school', models.CharField(default='', max_length=100)),
                ('schoolcertificatetype', models.CharField(default='', max_length=100)),
                ('schoolpercentage', models.CharField(default='', max_length=2)),
                ('jobcompany', models.CharField(default='', max_length=100)),
                ('jobdescription', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
